Initial Feedback
uniswapfoundation/v4-doc-drafts pull request #1
Opened 2024-06-19 21:16 UTC by adam0x7

Wrote a few concepts / reference docs. Looking for feedback to improve them!

2024-06-20 15:10 UTC, saucepoint requested changes
nice nice nice

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/ERC6909
> +Uniswap V4 utilizes the ERC-6909 standard to implement claim tokens, which represent user balances within the protocol. The `PoolManager` contract in Uniswap V4 inherits from the `ERC6909Claims` cont
for Protocol Concepts, we dont have to go into implementation details (i.e. the contract it inherits from and the functions it overrides)

I do think its worth describing 6909 vs 1155 (which you do at the beginning)

Overall this doc should explain where 6909 is used. It can be used for both inbound and outbound tokens for all lifecycle operations (swaps, liquidity, and donate). The benefits of 6909 are internal balance accounting (no external calls to USDC / USDT contract addresses). These are cheaper to use, and beneficial for MEV bots, high-frequency traders, and active liquidity management

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/Hooks.md
> +- Each liquidity pool in Uniswap V4 has its own hook contract attached to it.
```suggestion
- Each liquidity pool in Uniswap V4 can have its own hook contract attached to it.
```

(we want to imply that a pool can be hookless)

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/Hooks.md
> +- The `PoolManager` uses these permissions to determine which hook functions to call for a given pool.
worth mentioning that Pool's permissions are encoded in the address of the hook contract

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/Hooks.md
> +### Pool-Specific Hooks
add something that indicates that a Pool has only 1 hook contract. however, a hook contract can service multiple pairs

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/Hooks.md
> +- Developers can implement custom logic, perform additional checks, or modify parameters within these hook functions.
we should mention that hook contracts can mix and match / pick individual hook functions. Hook contracts are not limited to one hook and a hook contract does not have to implement all functions

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/Hooks.md
> +- These hooks allow developers to perform custom actions or validations during pool initialization.
because pools are initialized once, the initialization-hook-functions are invoked once

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/Hooks.md
> +- These hooks enable customization of liquidity management, such as [insert examples]
mention that liquidity hooks are granular for security purposes

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/PoolManager.md
> +- When unlocked, the calling contract can perform various operations and settle outstanding balances before returning control to the `PoolManager`
```suggestion
- When unlocked, the calling contract can perform various operations and zero-out outstanding balances before returning control to the `PoolManager` for final solvency checks
```

(try to refrain from using _settle_ to describe zero'ing out deltas because its a function name that specifically means to pay the PM. we've been using the terms zero-out or resolving)

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/PoolManager.md
> +- The `PoolManager` uses a locking mechanism to ensure atomicity and correctness of operations that happen in hooks
```suggestion
The `PoolManager` uses a locking mechanism to allow for _flash accounting_ (also known as deferred balance accounting)
```

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/PoolManager.md
> +- The `PoolManager` maintains a mapping called `_pools`, which associates a `PoolId` with its corresponding `Pool.State` struct
we can probably exclude this line, or at least make it more high-level. we can exclude implementation details from protocol concepts

2024-06-20 15:10 UTC, saucepoint commented on protocol-concepts/PoolManager.md
> +- Swaps are initiated through the `swap` function on the `PoolManager`
```suggestion
- Swaps are initiated through the `swap` function on the `PoolManager`, typically via a swap router contract
```

2024-06-20 15:10 UTC, saucepoint commented on reference-library/BalanceDelta.md
> +`BalanceDelta` is a type used in Uniswap V4 to represent the balance changes of two tokens (token0 and token1) in a single `int256` value. It is designed to efficiently store and manipulate these bal
```suggestion
`BalanceDelta` is a type used in Uniswap V4 to represent the balance changes of two tokens (token0 and token1). It tightly packs the two values in a single 256 bits. It is designed to efficiently store and manipulate these balance deltas, with the upper 128 bits representing the change in token0 (`amount0`) and the lower 128 bits representing the change in token1 (`amount1`).
```

2024-06-20 15:10 UTC, saucepoint commented on reference-library/BalanceDelta.md
> +At the end of the hook's execution, the `BalanceDelta` value should have `amount0` and `amount1` both equal to zero, indicating that the hook did not introduce any net balance changes. If the `Balanc
a bit misleading on a few fronts

1) balance deltas are not checked at the end of *hook* execution

2) hooks can modify the balances

---

generally i think you change this section to say that BalanceDeltas are forwarded to afterSwap and afterLiquidity functions

2024-06-20 15:10 UTC, saucepoint commented on reference-library/IPoolManager.md
> +The `IPoolManager` interface defines the main methods for interacting with the Uniswap V4 pool manager contract. It exposes the core liquidity management and swap functionality.
```suggestion
The `IPoolManager` interface defines the main methods for interacting with the Uniswap V4 pool manager contract. It exposes the core _swap lifecycle_ operations
```

2024-06-20 15:10 UTC, saucepoint commented on reference-library/IPoolManager.md
> +Initializes the state for a given pool ID with the specified parameters.
```suggestion
Initialize a new pool by defining its parameters: token pair, fee tier, tick spacing, hook contract, and starting price
```

2024-06-20 15:10 UTC, saucepoint commented on reference-library/IPoolManager.md
> +Modifies the liquidity for the given pool. Can be used to add, remove, or update a liquidity position.
```suggestion
Modifies the liquidity for the given pool. Can be used to add or remove liquidity, or collect fees

> passing zero will collect fees for the given tick range
```

2024-06-20 15:10 UTC, saucepoint commented on reference-library/IPoolManager.md
can we document the structs too. ModifyLiquidityParams and SwapParams

---

will be important to document that a negative liquidityDelta is a remove, and a negative amountSpecified is an exact-input swap

2024-06-22 15:56 UTC, adam0x7 commented on protocol-concepts/ERC6909
> +Uniswap V4 utilizes the ERC-6909 standard to implement claim tokens, which represent user balances within the protocol. The `PoolManager` contract in Uniswap V4 inherits from the `ERC6909Claims` cont
ok, found this as well that contrasts the differences.
https://github.com/Uniswap/v4-core/issues/357

2024-06-22 16:21 UTC, adam0x7 commented on reference-library/BalanceDelta.md
> +`BalanceDelta` is a type used in Uniswap V4 to represent the balance changes of two tokens (token0 and token1) in a single `int256` value. It is designed to efficiently store and manipulate these bal
the BalanceDelta portion has been the hardest one for me to understand so thanks for these explanations.

2024-06-25 15:14 UTC, merged